export const newsletterDataJson = [
	{
		id: 0,
		src: "/logos/worksinprogress.png",
		name: "The Works in Progress Newsletter",
		substackUrl: "https://www.worksinprogress.news",
		skystackUrl: "",
	},
	{
		id: 1,
		src: "/logos/fabricatedknowledge.png",
		name: "Fabricated Knowledge",
		substackUrl: "https://www.fabricatedknowledge.com/",
		skystackUrl: "",
	},
	{
		id: 2,
		src: "/logos/bismarckanalysis.png",
		name: "Bismarck Brief",
		substackUrl: "https://brief.bismarckanalysis.com/",
		skystackUrl: "",
	},
	{
		id: 3,
		src: "/logos/unchartedterritories.png",
		name: "Uncharted Territories",
		substackUrl: "https://unchartedterritories.tomaspueyo.com/",
		skystackUrl: "",
	},
	{
		id: 4,
		src: "/logos/newcomer.png",
		name: "Newcomer",
		substackUrl: "https://www.newcomer.co/",
		skystackUrl: "",
	},
	{
		id: 5,
		src: "/logos/dwarkesh.png",
		name: "Dwarkesh Podcast",
		substackUrl: "https://www.dwarkesh.com",
		skystackUrl: "",
	},
	{
		id: 6,
		src: "/logos/honest-broker.png",
		name: "The Honest Broker",
		substackUrl: "https://www.honest-broker.com/",
		skystackUrl: "",
	},
	{
		id: 7,
		src: "/logos/africanistperspective.png",
		name: "An Africanist Perspective",
		substackUrl: "https://www.africanistperspective.com/",
		skystackUrl: "",
	},
	{
		id: 8,
		src: "/logos/meaningness.png",
		name: "Meaningness",
		substackUrl: "https://meaningness.substack.com/",
		skystackUrl: "",
	},
	{
		id: 9,
		src: "/logos/derekthompson.png",
		name: "Derek Thompson",
		substackUrl: "https://www.derekthompson.org/",
		skystackUrl: "",
	},
	{
		id: 10,
		src: "/logos/astralcodexten.png",
		name: "Astral Codex Ten",
		substackUrl: "https://www.astralcodexten.com/",
		skystackUrl: "",
	},
	{
		id: 11,
		src: "/logos/robkhenderson.png",
		name: "Rob Henderson's Newsletter",
		substackUrl: "https://www.robkhenderson.com/",
		skystackUrl: "",
	},
	{
		id: 12,
		src: "/logos/statecraft.png",
		name: "Statecraft",
		substackUrl: "https://www.statecraft.pub",
		skystackUrl: "",
	},
	{
		id: 13,
		src: "/logos/theintrinsicperspective.png",
		name: "The Intrinsic Perspective",
		substackUrl: "https://www.theintrinsicperspective.com/",
		skystackUrl: "",
	},
	{
		id: 14,
		src: "/logos/thebulwark.png",
		name: "The Bulwark",
		substackUrl: "https://www.thebulwark.com",
		skystackUrl: "",
	},
	{
		id: 15,
		src: "/logos/cremieux.png",
		name: "Cremieux Recueil",
		substackUrl: "https://www.cremieux.xyz/",
		skystackUrl: "",
	},
	{
		id: 16,
		src: "/logos/noahpinion.png",
		name: "Noahpinion",
		substackUrl: "https://www.noahpinion.blog/",
		skystackUrl: "",
	},
	{
		id: 17,
		src: "/logos/ageofinvention.png",
		name: "Age of Invention, by Anton Howes",
		substackUrl: "https://www.ageofinvention.xyz/",
		skystackUrl: "",
	},
	{
		id: 18,
		src: "/logos/maximum-progress.png",
		name: "Maximum Progress",
		substackUrl: "https://www.maximum-progress.com",
		skystackUrl: "",
	},
	{
		id: 19,
		src: "/logos/experimentalhistory.png",
		name: "Experimental History",
		substackUrl: "https://www.experimental-history.com/",
		skystackUrl: "",
	},
	{
		id: 20,
		src: "/logos/constructionphysics.png",
		name: "Construction Physics",
		substackUrl: "https://www.construction-physics.com/",
		skystackUrl: "",
	},
	{
		id: 21,
		src: "/logos/instituteforprogress.png",
		name: "IFP",
		substackUrl: "https://instituteforprogress.substack.com",
		skystackUrl: "",
	},
	{
		id: 22,
		src: "/logos/slowboring.png",
		name: "Slow Boring",
		substackUrl: "https://www.slowboring.com",
		skystackUrl: "",
	},
	{
		id: 23,
		src: "/logos/kareem.png",
		name: "Kareem Abdul-Jabbar",
		substackUrl: "https://kareem.substack.com",
		skystackUrl: "",
	},
	{
		id: 24,
		src: "/logos/houseofstrauss.png",
		name: "House of Strauss",
		substackUrl: "https://www.houseofstrauss.com",
		skystackUrl: "",
	},
	{
		id: 25,
		src: "/logos/dominiccummings.png",
		name: "Dominic Cummings substack",
		substackUrl: "https://dominiccummings.substack.com",
		skystackUrl: "",
	},
	{
		id: 26,
		src: "/logos/louiseperry.png",
		name: "Maiden Mother Matriarch",
		substackUrl: "https://www.louiseperry.co.uk",
		skystackUrl: "",
	},
	{
		id: 27,
		src: "/logos/edwest.png",
		name: "Wrong Side of History",
		substackUrl: "https://www.edwest.co.uk",
		skystackUrl: "",
	},
	{
		id: 28,
		src: "/logos/persuasion.png",
		name: "Persuasion",
		substackUrl: "https://www.persuasion.community",
		skystackUrl: "",
	},
	{
		id: 29,
		src: "/logos/seymourhersh.png",
		name: "Seymour Hersh",
		substackUrl: "https://seymourhersh.substack.com/",
		skystackUrl: "",
	},
	{
		id: 30,
		src: "/logos/interconnects.png",
		name: "Interconnects",
		substackUrl: "https://www.interconnects.ai/",
		skystackUrl: "",
	},
	{
		id: 31,
		src: "/logos/emilkirkegaard.png",
		name: "Just Emil Kirkegaard Things",
		substackUrl: "https://www.emilkirkegaard.com",
		skystackUrl: "",
	},
	{
		id: 32,
		src: "/logos/slavoj.png",
		name: "ZIZEK GOADS AND PRODS",
		substackUrl: "https://slavoj.substack.com/",
		skystackUrl: "",
	},
	{
		id: 33,
		src: "/logos/henrikkarlsson.png",
		name: "Escaping Flatland",
		substackUrl: "https://www.henrikkarlsson.xyz/",
		skystackUrl: "",
	},
	{
		id: 34,
		src: "/logos/lennysnewsletter.png",
		name: "Lenny's Newsletter",
		substackUrl: "https://www.lennysnewsletter.com/",
		skystackUrl: "",
	},
	{
		id: 35,
		src: "/logos/graymirror.png",
		name: "Gray Mirror",
		substackUrl: "https://graymirror.substack.com/",
		skystackUrl: "",
	},
	{
		id: 36,
		src: "/logos/niallferguson.png",
		name: "Niall Ferguson's Time Machine",
		substackUrl: "https://niallferguson.substack.com/",
		skystackUrl: "",
	},
	{
		id: 37,
		src: "/logos/freddiedeboer.png",
		name: "Freddie deBoer",
		substackUrl: "https://freddiedeboer.substack.com",
		skystackUrl: "",
	},
	{
		id: 38,
		src: "/logos/newsletter.png",
		name: "The Roots of Progress",
		substackUrl: "https://newsletter.rootsofprogress.org/",
		skystackUrl: "",
	},
	{
		id: 39,
		src: "/logos/asianometry.png",
		name: "The Asianometry Newsletter",
		substackUrl: "https://www.asianometry.com",
		skystackUrl: "",
	},
	{
		id: 40,
		src: "/logos/balajis.png",
		name: "balajis.com",
		substackUrl: "https://balajis.com",
		skystackUrl: "",
	},
	{
		id: 41,
		src: "/logos/daviddfriedman.png",
		name: "David Friedman's Substack",
		substackUrl: "https://daviddfriedman.substack.com",
		skystackUrl: "",
	},
	{
		id: 42,
		src: "/logos/economicforces.png",
		name: "Economic Forces",
		substackUrl: "https://www.economicforces.xyz",
		skystackUrl: "",
	},
	{
		id: 43,
		src: "/logos/gwern.png",
		name: "Gwern.net Newsletter",
		substackUrl: "https://gwern.substack.com",
		skystackUrl: "",
	},
	{
		id: 44,
		src: "/logos/courtenaypipkin.png",
		name: "the honest yoga teacher",
		substackUrl: "https://courtenaypipkin.substack.com",
		skystackUrl: "",
	},
	{
		id: 45,
		src: "/logos/racket.png",
		name: "Racket News",
		substackUrl: "https://www.racket.news",
		skystackUrl: "",
	},
	{
		id: 46,
		src: "/logos/johnathanbi.png",
		name: "Johnathan Bi",
		substackUrl: "https://www.johnathanbi.com",
		skystackUrl: "",
	},
	{
		id: 47,
		src: "/logos/chuckpalahniuk.png",
		name: "Chuck Palahniuk's Plot Spoiler",
		substackUrl: "https://chuckpalahniuk.substack.com/",
		skystackUrl: "",
	},
	{
		id: 48,
		src: "/logos/thefp.png",
		name: "The Free Press",
		substackUrl: "https://www.thefp.com",
		skystackUrl: "",
	},
	{
		id: 49,
		src: "/logos/nabeelqu.png",
		name: "Nabeel S. Qureshi",
		substackUrl: "https://nabeelqu.substack.com",
		skystackUrl: "",
	},
	{
		id: 50,
		src: "/logos/overcomingbias.png",
		name: "Overcoming Bias",
		substackUrl: "https://www.overcomingbias.com",
		skystackUrl: "",
	},
	{
		id: 51,
		src: "/logos/letter.png",
		name: "The Palladium Letter",
		substackUrl: "https://letter.palladiummag.com",
		skystackUrl: "",
	},
	{
		id: 52,
		src: "/logos/richardhanania.png",
		name: "Richard Hanania's Newsletter",
		substackUrl: "https://www.richardhanania.com",
		skystackUrl: "",
	},
	{
		id: 53,
		src: "/logos/sashachapin.png",
		name: "Sasha's Newsletter",
		substackUrl: "https://sashachapin.substack.com",
		skystackUrl: "",
	},
	{
		id: 54,
		src: "/logos/razibkhan.png",
		name: "Razib Khan's Unsupervised Learning",
		substackUrl: "https://www.razibkhan.com/",
		skystackUrl: "",
	},
	{
		id: 55,
		src: "/logos/techbuzzchina.png",
		name: "Tech Buzz China Insider",
		substackUrl: "https://techbuzzchina.substack.com",
		skystackUrl: "",
	},
	{
		id: 56,
		src: "/logos/understandingai.png",
		name: "Understanding AI",
		substackUrl: "https://www.understandingai.org",
		skystackUrl: "",
	},
	{
		id: 57,
		src: "/logos/mattsclancy.png",
		name: "What's New Under the Sun",
		substackUrl: "https://mattsclancy.substack.com",
		skystackUrl: "",
	},
	{
		id: 58,
		src: "/logos/pragmaticengineer.png",
		name: "The Pragmatic Engineer",
		substackUrl: "https://newsletter.pragmaticengineer.com/",
		skystackUrl: "",
	},
	{
		id: 59,
		src: "/logos/zeteo.png",
		name: "Zeteo",
		substackUrl: "https://zeteo.com",
		skystackUrl: "",
	},
];
